spring:
  application:
  name: return-predictor-backend
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.returnpredictor.api.controller.ReturnPredictionController: WARN
    com.returnpredictor: INFO
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG